# Site settings
title: Jordon Mears
tagline: while(true) { write(learn(live())); }
description: >
  Software engineer focused on geo, video game enthusiast and occasional
  cyclist.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
linkedin_username: jordoncm
github_username: jordoncm

# Build settings
markdown: kramdown
